### PR TITLE
Add new statuses

### LINKED ISSUE #122: Introduce "Not Sent" status of orders
There should be another status "Not Sent". This status can occur when an order that is with status "ordered" was not marked as sent for 7 days.

### PR DESCRIPTION
**Pull request by julkascript**
Closes #122 

- [x] Add `not_sent` and `not_received` statuses. 
- [x] Disable seller to mark order as "Sent" / "Completed".

Next steps:
- #123 
- Add Not Received option in [Milestone v1.4](https://github.com/julkascript/cardflow/milestone/5)

### CODE REVIEW

**Review by dinocom33 — APPROVED** [review]
Looks good to me.

**Comment by RyotaMitaraiWeb** [comment]
- you should update the OrdersModal's "Not Received" radio to use the ``not_received`` status as value (it currently uses ``rejected`` which was done with the idea that it'd be updated at a later point)
  - (the relevant line is 159)
- also, not sure if this is intended, but I managed to send a review for a "not sent" order, I don't think it logically makes sense to allow a review, since there's nothing to review
- not sure if it's an issue on my end, but I receive a 500 internal error if I try to change the status to ``not_sent`` or ``not_received`` via the PATCH endpoint (I tested this with an order marked as ``ordered``, later on ``sent``). While you logically shouldn't be able to change the status to ``not_sent``, this will cause issues for the latter option. Also, for whatever reason, it only activates for those two, giving non-existant statuses returns the correct status code. I tried deleting the Postgres volume to make sure it wasn't some issue with migrations, but no dice.

error for reference:

```
ValueError at /api/order/1/
'not_received' is not in list

Request Method: PATCH
Request URL: http://localhost:8000/api/order/1/
Django Version: 4.2.6
Python Executable: /usr/local/bin/python
Python Version: 3.11.4
Python Path: ['/usr/src/app', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages']
Server time: Sat, 22 Jun 2024 18:36:08 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'rest_framework_simplejwt',
 'corsheaders',
 'accounts.apps.AccountsConfig',
 'game',
 'card',
 'yugioh',
 'listing',
 'drf_spectacular',
 'order',
 'cart',
 'django_cleanup.apps.CleanupConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
    ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/order/serializers.py", line 56, in update
    if self.get_status_index(validated_data['status']) < self.get_status_index(instance.status):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/order/serializers.py", line 83, in get_status_index
    return status_order.index(status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: ValueError at /api/order/1/
Exception Value: 'not_received' is not in list
Raised during: order.views.OrderViewSet
Request information:
USER: admin
```

**Comment by RyotaMitaraiWeb** [comment]
I managed to fix most of these myself. In particular:

- updated the front end to send the correct value
- I managed to fix the 500 error I was receiving earlier. The reason it occurred was because of a validation for status downgrade; more specifically, when the corresponding view tried to see if the status is being downgraded (e.g. sent -> ordered), it threw an exception because the new statuses weren't in the list it was looking up.
- I also updated the migrations, as it caused me another 500 error (in particular, the status for the order history and order models were mismatched and caused issues with Django's own model validation, though it worked internally on database level)
- I also made sure that a user cannot change an order's status once it is marked as not sent or not received. I have also changed the error message to be more inclusive and so that we don't have to update it if we have to add a new status with similar conditions.

**Not done (out of scope / will be solved later):**
- currently, I haven't done anything to block feedbacks to orders marked as not sent or not received, as it will be out of scope for this issue + there aren't any server-side checks yet for that (so might as well combine them all in a single issue)
- on the front end currently, if you change an order's status to not received or not state, the toast will display the status as "not_sent" or "not_received" (notice the underscore). This is not tackled, as my soon-to-come internalization PR will handle this (it's almost done + I need this to be merged first)

I don't have particular experience with Django, so apologies if I screwed anything up

**Review by RyotaMitaraiWeb — APPROVED** [review]

**Review by milensski — APPROVED** [review]
@RyotaMitaraiWeb  Good job, it looks good in Django - it is well written to me and it works.

> currently, marking an order as not sent or not received will still deplete the quantity of the listing and won't revert it. I haven't changed anything because I am not sure what the correct behavior would be

I was thinking the same and in my opinion it should do something, maybe to delist the whole listing as a punishment to the seller and to prevent further purchases before he looks it and turn it as listed again.

**Pull request merged**
