### PR TITLE
Trade

### PR DESCRIPTION
**Pull request by dinocom33**
This PR represents Trade functionality(issue #116 ).
When a user initiates a new trade, he becomes the ```initiator``` and his ```initiator_decision``` is automatically filled in as accepted and the status of the trade becomes ```Negotiate```.
If one of the users rejects the trade, it automatically becomes ```Rejected```, the trade is closed and cannot be changed anymore.
If they both accept the trade, it's becomes ```Accepted```.
Users can only trade their listings which are marked as ```is_listed```.

### CODE REVIEW

**Comment by julkascript** [comment]
I tried Trade create request with body:
```json
{
    "initiator_listing": [
        1
    ],
    "recipient_listing": [
        2
    ],
    "initiator_cash": 5,
    "recipient_cash": 0,
    "initiator_decision": "pending",
    "recipient_decision": "pending"
}
```

but I get error: `"You can not trade with recipient's listing ids: [2]."`. Id 2 is a valid target, because that is another user. I am currently logged in as user 1, and I am using its token. I get the same error when I try with other ids.

**Comment by julkascript** [comment]
Also, I think it will be easier if we enforce the `recipient id` (currently we obtain it like `recipient = recipient_listing[0].user`, which is easy to get around).  Then check if all listings you are trying to trade are really of this user and this user only.

**Comment by julkascript** [comment]
Otherwise looks good!

**Comment by dinocom33** [comment]
Fixed. Now the POST request looks like bellow:
```
{
    "recipient": 4,
    "initiator_listing": [
        3, 4
    ],
    "recipient_listing": [
        14
    ],
    "initiator_cash": 5,
    "recipient_cash": 0,
    "initiator_decision": "pending",
    "recipient_decision": "pending"
}
```

**Review by julkascript — APPROVED** [review]

**Pull request merged**
